version: "3.9"
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: cocov
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  api:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - root_home:/root
      - ./script/.irbrc:/root/.irbrc:ro
    depends_on:
      - postgres
      - redis
    ports:
      - 3000:3000
    env_file: .env
volumes:
  bundle:
  root_home:
